const INTERNAL_SERVER_ERROR_MESSAGE = "Something went wrong! please try again later.";

const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

const BAD_REQUEST_STATUS_CODE = 400;

const NOT_FOUND_REQUEST_STATUS_CODE = 404;

module.exports = {
    INTERNAL_SERVER_ERROR_MESSAGE, 
    INTERNAL_SERVER_ERROR_STATUS_CODE, 
    BAD_REQUEST_STATUS_CODE,
    NOT_FOUND_REQUEST_STATUS_CODE
}